### ISSUE TITLE
Are arguments --overwrite and --remove needed?

### ISSUE THREAD

**Issue by callmekatootie** [peter-evans/s3-backup#17]
Per the Readme, I need to define my action with:

```
        with:
          args: --overwrite --remove

```

but I could not find this being used in the entrypoint.sh file. Is that really needed?

**Comment by peter-evans** [comment]
The args are used on this line (`$*`):

https://github.com/peter-evans/s3-backup/blob/2a981ddc0e67534918d5e4a014d4acf8d8f11384/entrypoint.sh#L24C11-L24C13

**Comment by callmekatootie** [comment]
_ah_ I missed those 2 characters! My bad. Thank you.
